# Generated by Django 3.2.21 on 2023-09-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhyatm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adhyatmjagat',
            name='main_image',
            field=models.ImageField(null=True, upload_to='adhyatm_jagat_image'),
        ),
    ]
