# Generated by Django 3.2.21 on 2023-09-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhyatm', '0002_adhyatmjagat_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhyatmjagat',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='adhyatm_jagat_image'),
        ),
    ]
