# Generated by Django 3.2.21 on 2023-09-30 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, null=True)),
                ('desc', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=1000, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.TextField(null=True)),
                ('website', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('timing_from1', models.CharField(blank=True, max_length=50, null=True)),
                ('timing_to1', models.CharField(blank=True, max_length=50, null=True)),
                ('timing_from2', models.CharField(blank=True, max_length=50, null=True)),
                ('timing_to2', models.CharField(blank=True, max_length=50, null=True)),
                ('holiday', models.CharField(blank=True, max_length=500, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='store_image')),
                ('other_image1', models.ImageField(blank=True, null=True, upload_to='store_image')),
                ('other_image2', models.ImageField(blank=True, null=True, upload_to='store_image')),
                ('store_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.storetype')),
            ],
        ),
    ]
