# Generated by Django 4.2.2 on 2023-06-18 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, null=True)),
                ('desc', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=1000, null=True)),
                ('desc', models.TextField(null=True)),
                ('add', models.TextField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('timing_from1', models.CharField(max_length=50)),
                ('timing_to1', models.CharField(max_length=50)),
                ('timing_from2', models.CharField(max_length=50)),
                ('timing_to2', models.CharField(max_length=50)),
                ('holiday', models.CharField(max_length=500, null=True)),
                ('owner_name', models.CharField(max_length=500, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('store_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.storetype')),
            ],
        ),
    ]
