# Generated by Django 4.0 on 2023-07-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='add',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='store',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='store',
            name='mobile',
        ),
        migrations.AddField(
            model_name='store',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='store_image'),
        ),
        migrations.AddField(
            model_name='store',
            name='other_image1',
            field=models.ImageField(blank=True, null=True, upload_to='store_image'),
        ),
        migrations.AddField(
            model_name='store',
            name='other_image2',
            field=models.ImageField(blank=True, null=True, upload_to='store_image'),
        ),
        migrations.AddField(
            model_name='store',
            name='website',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='holiday',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='owner_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='timing_from1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='timing_from2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='timing_to1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='timing_to2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
