# Generated by Django 3.2.21 on 2023-09-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temple', '0002_rename_add_temple_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='temple',
            name='main_img',
            field=models.ImageField(default=None, null=True, upload_to='temple_image'),
        ),
    ]
