# Generated by Django 4.0 on 2023-07-22 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HealthService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('address', models.TextField(null=True)),
                ('opening_day', models.CharField(default='Monday-Saturday', max_length=50, null=True)),
                ('holiday', models.CharField(blank=True, default='Sunday', max_length=50, null=True)),
                ('emergency_cases', models.BooleanField(blank=True, default=False, null=True)),
                ('emergency_time', models.CharField(blank=True, default='24 hours', max_length=50, null=True)),
                ('available_doctors', models.IntegerField(null=True)),
                ('appointment_contact_no', models.CharField(max_length=15, null=True)),
                ('hospital_contact_no', models.CharField(max_length=15, null=True)),
                ('hospital_specialities', models.CharField(max_length=1000, null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='health_service.healthtype')),
            ],
        ),
    ]
