# Generated by Django 4.0 on 2023-07-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthservice',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='health_image'),
        ),
        migrations.AddField(
            model_name='healthservice',
            name='other_image1',
            field=models.ImageField(blank=True, null=True, upload_to='health_image'),
        ),
        migrations.AddField(
            model_name='healthservice',
            name='other_image2',
            field=models.ImageField(blank=True, null=True, upload_to='health_image'),
        ),
    ]
