# Generated by Django 4.0 on 2023-07-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_service', '0002_healthservice_main_image_healthservice_other_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthservice',
            name='appointment_contact_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='healthservice',
            name='available_doctors',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthservice',
            name='hospital_contact_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='healthservice',
            name='hospital_specialities',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
