# Generated by Django 4.0 on 2023-07-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_service', '0003_alter_healthservice_appointment_contact_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthservice',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='healthservice',
            name='website',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
