# Generated by Django 4.0 on 2023-07-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_service', '0004_healthservice_email_healthservice_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthservice',
            name='main_image',
            field=models.ImageField(null=True, upload_to='health_image'),
        ),
    ]
