# Generated by Django 4.0 on 2023-07-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, null=True)),
                ('address', models.TextField(null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('contact_number', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.TextField(blank=True, null=True)),
                ('year_of_establish', models.CharField(blank=True, max_length=30, null=True)),
                ('timing', models.CharField(blank=True, max_length=30, null=True)),
                ('affilliated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('courses_list', models.TextField(blank=True, null=True)),
                ('facilities', models.TextField(blank=True, null=True)),
                ('medium_language', models.CharField(blank=True, max_length=100, null=True)),
                ('school_class', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.CharField(blank=True, max_length=500, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=100, null=True)),
                ('owner_contact', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
