# Generated by Django 4.0 on 2023-07-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_sector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationsector',
            name='main_image',
            field=models.ImageField(null=True, upload_to='education_image'),
        ),
        migrations.AddField(
            model_name='educationsector',
            name='other_image1',
            field=models.ImageField(blank=True, null=True, upload_to='education_image'),
        ),
        migrations.AddField(
            model_name='educationsector',
            name='other_image2',
            field=models.ImageField(blank=True, null=True, upload_to='education_image'),
        ),
        migrations.AddField(
            model_name='educationsector',
            name='other_image3',
            field=models.ImageField(blank=True, null=True, upload_to='education_image'),
        ),
    ]
